# configurations:
# - deployment-rollout.yaml

configurations:
- rollout-transform.yaml

images:
- name: maverick0803/spinint3notejamdev
  newTag: "3"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../application
