# configurations:
# - deployment-rollout.yaml

# configurations:
# - rollout-transform.yaml

patches:
- path: patch-canary.yaml
  target:
    group: argoproj.io
    kind: Rollout
    version: v1alpha1

images:
- name: maverick0803/spinint3notejamdev
  newTag: "4"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../application
