# configurations:
# - deployment-rollout.yaml

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

images:
- name: maverick0803/spinint3notejamdev
  newTag: "39"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../application
