apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

configurations:
- rollout-transform.yaml

resources:
- notejam-ingress.yaml
- notejam-service.yaml
- deployment.yaml
- deployment-rollout.yaml
